### ISSUE TITLE
Ne fonctionne plus

### ISSUE THREAD

**Issue by thorvak** [chneau/warket#2]
panic: invalid character '<' looking for beginning of value

goroutine 1 [running]:
github.com/chneau/warket/display.NewTable(0xc0000a00e0, 0x9, 0xc00050c000, 0x6c, 0x8d, 0x86a0d3, 0x3, 0x0, 0x0, 0x0, ...)
        C:/Users/CEDRIC/go/src/github.com/chneau/warket/display/table.go:180 +0x9bd
github.com/chneau/warket/display.(*TableContext).PrepareTable(0xc00058dc58, 0xc0002a9770, 0x8701e2)
        C:/Users/CEDRIC/go/src/github.com/chneau/warket/display/tableContext.go:73 +0x27d
github.com/chneau/warket/display.(*TableContext).Run(0xc00058dc58)
        C:/Users/CEDRIC/go/src/github.com/chneau/warket/display/tableContext.go:46 +0x285
github.com/chneau/warket/cmd.Watch(0xc000072e80, 0xc00032b2c0, 0x6)
        C:/Users/CEDRIC/go/src/github.com/chneau/warket/cmd/watch.go:26 +0x261
github.com/urfave/cli.(*Command).Run(0xc0000c45a0, 0xc000072b80, 0x0, 0x0)
        C:/Users/CEDRIC/go/src/github.com/urfave/cli/command.go:163 +0x4e7
github.com/urfave/cli.(*App).RunContext(0xc0000c6340, 0x90c940, 0xc0000a00c8, 0xc0000d2000, 0x5, 0x8, 0x0, 0x0)
        C:/Users/CEDRIC/go/src/github.com/urfave/cli/app.go:313 +0x81b
github.com/urfave/cli.(*App).Run(...)
        C:/Users/CEDRIC/go/src/github.com/urfave/cli/app.go:224
main.main()
        C:/Users/CEDRIC/go/src/github.com/chneau/warket/main.go:95 +0x8cc

**Comment by chneau** [comment]
Yo ca devrait fonctionner maintenant :)
